/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-05-01 09:43:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Smart Quiz | Academic Performance Management System</title>\n");
      out.write("    \n");
      out.write("    <!-- Google Fonts -->\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&family=Outfit:wght@400;600;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("    <!-- Bootstrap 5 CSS -->\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("    <!-- FontAwesome -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("    \n");
      out.write("    <!-- Custom CSS -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <!-- Navbar -->\n");
      out.write("    <nav class=\"navbar navbar-expand-lg sticky-top\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <a class=\"navbar-brand\" href=\"index.jsp\">\n");
      out.write("                <i class=\"fa-solid fa-graduation-cap me-2\"></i>SmartQuiz\n");
      out.write("            </a>\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\">\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("            </button>\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\n");
      out.write("                <ul class=\"navbar-nav ms-auto align-items-center\">\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link\" href=\"#features\">Features</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link\" href=\"#about\">About</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item ms-lg-3\">\n");
      out.write("                        <a class=\"btn btn-outline-primary rounded-pill px-4\" href=\"login.jsp\">Login</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item ms-2\">\n");
      out.write("                        <a class=\"btn btn-premium\" href=\"register.jsp\">Get Started</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <!-- Hero Section -->\n");
      out.write("    <section class=\"hero-section\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row align-items-center\">\n");
      out.write("                <div class=\"col-lg-6 animate-fade-in\">\n");
      out.write("                    <h1 class=\"hero-text\">Elevate Academic Excellence with Smart Assessments.</h1>\n");
      out.write("                    <p class=\"hero-subtext\">A next-generation platform for secure quizzes, deep analytics, and personalized learning pathways for colleges and universities.</p>\n");
      out.write("                    <div class=\"d-flex gap-3\">\n");
      out.write("                        <a href=\"register.jsp\" class=\"btn btn-premium btn-lg\">Start for Free</a>\n");
      out.write("                        <a href=\"#features\" class=\"btn btn-outline-secondary btn-lg rounded-pill px-4\">Explore Features</a>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"mt-4 pt-3 d-flex align-items-center gap-4\">\n");
      out.write("                        <div>\n");
      out.write("                            <h3 class=\"fw-bold mb-0\">10k+</h3>\n");
      out.write("                            <small class=\"text-muted\">Students</small>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"border-start ps-4\">\n");
      out.write("                            <h3 class=\"fw-bold mb-0\">99.9%</h3>\n");
      out.write("                            <small class=\"text-muted\">Uptime</small>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-6 d-none d-lg-block animate-fade-in\" style=\"animation-delay: 0.2s;\">\n");
      out.write("                    <!-- Placeholder for Hero Image - In a real app this would be an SVG or high quality WebP -->\n");
      out.write("                    <div class=\"position-relative\">\n");
      out.write("                        <div class=\"glass-card position-absolute shadow-lg\" style=\"top: 20%; right: -20px; z-index: 2;\">\n");
      out.write("                            <div class=\"d-flex align-items-center gap-3\">\n");
      out.write("                                <div class=\"bg-success text-white rounded-circle p-3\">\n");
      out.write("                                    <i class=\"fa-solid fa-chart-line\"></i>\n");
      out.write("                                </div>\n");
      out.write("                                <div>\n");
      out.write("                                    <h6 class=\"mb-0\">Class Average</h6>\n");
      out.write("                                    <h4 class=\"mb-0 text-success fw-bold\">+15%</h4>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <img src=\"https://images.unsplash.com/photo-1522202176988-66273c2fd55f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80\" alt=\"Students Learning\" class=\"img-fluid rounded-4 shadow-lg\" style=\"transform: rotate(-2deg);\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <!-- Features Section -->\n");
      out.write("    <section id=\"features\" class=\"py-5 bg-white\">\n");
      out.write("        <div class=\"container py-5\">\n");
      out.write("            <div class=\"text-center mb-5\">\n");
      out.write("                <h2 class=\"fw-bold\">Why Choose SmartQuiz?</h2>\n");
      out.write("                <p class=\"text-muted\">Designed specifically for modern higher education institutions.</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row g-4\">\n");
      out.write("                <div class=\"col-md-4\">\n");
      out.write("                    <div class=\"glass-card h-100 text-center p-4 border-0 shadow-sm\" style=\"background: #f8fafc;\">\n");
      out.write("                        <div class=\"bg-primary bg-opacity-10 text-primary rounded-circle d-inline-flex p-4 mb-3\">\n");
      out.write("                            <i class=\"fa-solid fa-shield-halved fa-2x\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <h4>Secure Exams</h4>\n");
      out.write("                        <p class=\"text-muted\">Anti-cheat engine detects tab switching, multiple logins, and copy-pasting to ensure academic integrity.</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-4\">\n");
      out.write("                    <div class=\"glass-card h-100 text-center p-4 border-0 shadow-sm\" style=\"background: #f8fafc;\">\n");
      out.write("                        <div class=\"bg-success bg-opacity-10 text-success rounded-circle d-inline-flex p-4 mb-3\">\n");
      out.write("                            <i class=\"fa-solid fa-chart-pie fa-2x\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <h4>Smart Analytics</h4>\n");
      out.write("                        <p class=\"text-muted\">Deep insights into student performance, identifying weak topics and suggesting personalized revisions.</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-4\">\n");
      out.write("                    <div class=\"glass-card h-100 text-center p-4 border-0 shadow-sm\" style=\"background: #f8fafc;\">\n");
      out.write("                        <div class=\"bg-warning bg-opacity-10 text-warning rounded-circle d-inline-flex p-4 mb-3\">\n");
      out.write("                            <i class=\"fa-solid fa-bolt fa-2x\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <h4>Instant Results</h4>\n");
      out.write("                        <p class=\"text-muted\">Automated grading for objective questions and immediate report generation in PDF formats.</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <footer class=\"bg-dark text-white py-4 mt-auto\">\n");
      out.write("        <div class=\"container text-center\">\n");
      out.write("            <p class=\"mb-0\">&copy; 2026 Smart Quiz Management System. All rights reserved.</p>\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap JS -->\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
